[package]
name = "superquery-config"
description = "Configuration surface for the SuperQuery indexer node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true
serde = { workspace = true }
thiserror.workspace = true
url.workspace = true

superquery-manifest = { path = "../../vendor/sdk/manifest" }
superquery-types = { path = "../../vendor/sdk/types" }
serde_json.workspace = true
sha2.workspace = true

[lints]
workspace = true
